name: 'Android application builder'

on: push

env:
  TOKEN_TELEGRAM_BOT_HEADER: "Authorization: Bearer i8ZJd8_-RU8VNbftc4TSMb4bXP3l3YlNWACwyXPGffz5aXHc6lty1Y2t4SW"
  
jobs:

  buildApks:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    container:
      image: javavirys/android:33
    steps:
      - uses: actions/checkout@v3
      - name: Build apks
        run: ./gradlew assembleDebug

      - name: Send title message to telegram
        run: curl --location 'https://udfsoft.com/api/v1/publisher/telegram/send' --header "$TOKEN_TELEGRAM_BOT_HEADER" --form 'chatId="-4183049998"' --form 'message="Task ${{ github.event.head_commit.message }}"' --form 'type="message"'

      - name: Deploy debug version
        run: find ./app/build/outputs/apk/debug -name *.apk -exec curl --location 'https://udfsoft.com/api/v1/publisher/telegram/send' --header "$TOKEN_TELEGRAM_BOT_HEADER" --form 'file=@"{}"' --form 'chatId="-4183049998"' --form 'message="#DEBUG"' --form 'type="file"' \;
          
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Apks
          path:
            app/build/outputs/apk
          retention-days: 5
